FROM node:22-alpine

ENV PRISMA_CLI_QUERY_ENGINE_TYPE=none

WORKDIR /app

COPY prisma.config.ts .
COPY prisma ./prisma
RUN npm install --no-save prisma dotenv

CMD ["npx", "prisma", "migrate", "deploy"]
